<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
        <UserSecretsId>facf0858-cf43-4d1a-8ed4-d1f8cb60cf19</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Generator.Equals" Version="4.1.0" />
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.200" Condition="'$(Configuration)' == 'Debug'">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="18.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
        <PackageReference Include="RestSharp" Version="114.0.0" />
        <PackageReference Include="DotMake.CommandLine" Version="3.6.0" />
        <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
        <PackageReference Include="Spectre.Console" Version="0.57.2" />
        <PackageReference Include="Spectre.Console.Json" Version="0.57.2" />
        <PackageReference Include="YamlDotNet" Version="18.1.0" />
    </ItemGroup>
</Project>