<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Generator.Equals" Version="3.3.0" />
        <PackageReference Include="Meziantou.Analyzer" Version="2.0.296" Condition="'$(Configuration)' == 'Debug'">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.2.0" />
        <PackageReference Include="RestSharp" Version="113.1.0" />
        <PackageReference Include="DotMake.CommandLine" Version="3.1.0" />
        <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
        <PackageReference Include="Spectre.Console" Version="0.54.0" />
        <PackageReference Include="Spectre.Console.Json" Version="0.54.0" />
        <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="16.3.0" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>
</Project>